### ISSUE TITLE
Ensure dataset has unique images

### ISSUE THREAD

**Issue by urmzd** [urmzd/rabbit-classifier#18]
# Purpose

Detect and remove any duplicates found using [difPy](https://github.com/elisemercury/Duplicate-Image-Finder).

**Comment by urmzd** [comment]
@ksek87 @Benjmacdonald can one of you guys run this?

**Comment by ksek87** [comment]
Script Results:
    Found 1 image with one or more duplicate/similar images in 3.1972 seconds.
    {'40.jpg': {'location': 'images/40.jpg', 'duplicates': ['images/8.jpg']}}

Commit: 91e5921459c9be7eb78616def8485ecf6b15d0d6
